# docker-compose.yml

version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: pg_projet3_nestjs
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5435:5432'

volumes:
  postgres_data:
